#
# Makefile for CIT 595 Project
# Group 7: Yue Chen, Linjie Peng, Luyao Wang
#

all: server

server: server.cpp
	c++ -lpthread -o server server.cpp


clean:
	rm -rf *.o

clobber: clean
	rm -rf server
	
